# fly.toml file generated for dounot-superfast on 2022-02-28T12:04:20+01:00

app = "dounot-superfast"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  CRYSTALLIZE_TENANT_IDENTIFIER = "dounot"
  SERVICE_API_URL = "https://product-storytelling-service-api.vercel.app/api/graphql"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
